---

- name: "Update System"
  package:
    state: latest
    name: "*"

- name: "Install Essential Packages"
  apt:
    state: present
    name: "{{ item }}"
  loop: "{{ packages.to_install }}"

- name: "Enable Essential Services"
  apt:
    state: present
    name: "{{ item }}"
  loop: "{{ services.to_enable }}"

- name: "Configure NTP service"
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    mode: 0644
  notify: "Restart NTP service"

- name: "Hardening - Kernel Parameters"
  template:
    src: 11-hardening.conf.j2
    dest: /etc/sysctl.d/11-hardening.conf
    owner: root
    group: root
    mode: 0644
  notify: "Apply Kernel Parameters"